### PR TITLE
PLATE-387 add libs for creating buildkite pipelines using Typescript

### PR DESCRIPTION
**Pull request by micheal-hill**
Some things to note:
- Pipelines are run with Deno to better lockdown access - no network access (except to download libs) and no execution of arbitrary shell commands.
- Editing Deno is best done with VSCode. The Intellij plugin for it is garbage.
- Deno does not support node modules or many Node APIs. It does have it's own alternatives to these.

### CODE REVIEW

**Comment by nmc-ailo** [comment]
Just a general comment, when I saw `env` my initial thoughts was that this related to our deployment envs (eg Dev, QA, etc), it took me a little bit to realize it's actually the environmental variables.  Just wondering would using say `environment` or `env_var` name be more helpful, what do you think?

**Comment by micheal-hill** [comment]
> Just a general comment, when I saw `env` my initial thoughts was that this related to our deployment envs (eg Dev, QA, etc), it took me a little bit to realize it's actually the environmental variables. Just wondering would using say `environment` or `env_var` name be more helpful, what do you think?

eg. [here](https://github.com/ailohq/buildkite-utils/blob/9ee57810a67821cf97680c84ed890154f12857c6/.buildkite/pipeline.ts#L45)? Can change that to longer `environment`. It was the short form only because that's what BK already uses, but I think in this case it's easy to do it different.

**Comment by nmc-ailo** [comment]
more the `env`'s in the util code, the pipeline is another place but, of course depending how big the file is, is probably easier to recognise.  Not a biggie just sharing something that happened as I was digesting the PR. :-)

**Comment by micheal-hill** [comment]
@nmc-ailo I've updated the lib to use `environment` instead of `env` everywhere I could see; does this help?

**Review by nmc-ailo — APPROVED** [review]
lgtm (and learnt some :-)) 👍

**Pull request merged**
